"""empty message

Revision ID: 61bea937cd38
Revises: bec91c6fff1b
Create Date: 2020-05-21 20:51:33.806684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bea937cd38'
down_revision = 'bec91c6fff1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_link')
    # ### end Alembic commands ###
