"""empty message

Revision ID: a338f398e1f4
Revises: e1f23916090c
Create Date: 2020-05-24 17:57:48.195923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a338f398e1f4'
down_revision = 'e1f23916090c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'discount')
    op.drop_column('cart', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('discount', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
