"""empty message

Revision ID: c2e67315063a
Revises: c57cd9afecfb
Create Date: 2020-06-10 19:17:28.113322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2e67315063a'
down_revision = 'c57cd9afecfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('external_id', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('first_name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('last_name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('adress', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('neighborhood', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('role_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('country', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['roles.id'], name='user_role_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='user_pkey')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('role', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR()),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='roles_pkey')
                    )
    # ### end Alembic commands ###
